spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.syqbivbvcpgugmpjwzfo&password=gNQKwIekWEibHwxX
    username: postgres.syqbivbvcpgugmpjwzfo
    password: gNQKwIekWEibHwxX
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
